### ISSUE TITLE
add mouse wheel to zoom in and out in GUI

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#117]
https://github.com/qindapao/P5-App-Asciio/commit/e10bddd7c44439052de5a9e3d904034f13b81924

@nkh 

It should be convenient to do this on the GUI. Because the default mouse wheel operation is to drag the scroll bar up and down. So I gave Ctrl+mousewheel

Also I changed one more thing

![room_err](https://github.com/nkh/P5-App-Asciio/assets/109883544/919782c6-71a2-42ff-8463-1db497adddb1)

This is the previous room operation. You can see that the relative position of the element has changed.This may not be what the user wants

![room_right](https://github.com/nkh/P5-App-Asciio/assets/109883544/6e85d5ff-d7a3-4e92-90e1-279e3fda0403)

This is changed, try to keep the relative position of the elements static when the scroll bar is adjustable. However, it still cannot be adjusted when the scroll bar has reached both ends.

**Comment by nkh** [comment]
@qindapao I agree, let me check it and merge

**Comment by nkh** [comment]
I squashed:
1a9fde1 FIXED: code review for mouse scroll  (quin/add_mouse_scroll) (8 days ago, QinQing)
e10bddd ADDED: mouse scroll room in and out  (11 days ago, QinQing)

into:
4163b43 ADDED: mouse scroll zoom in and out  (HEAD -> master, origin/master, origin/HEAD) (11 days ago, QinQing)

You can update your master and throw away your *add_mouse_scroll* branch

As I wrote earlier, 'C00-scroll-up/down' are not signals I get on my machine, so your patch doesn't work for me, probably because my laptop doesn't have a scroll button, I will have a look at it.

**Comment by qindapao** [comment]
@nkh 

I use a traditional physical mouse with a scroll wheel. Can scroll up and down. Maybe your laptop's mouse is a different thing, maybe we can fix it with an upgrade.
