### ISSUE TITLE
Should arrows have connectors?

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#133]
two pronged arrow

arrow connect to another arrow

**Comment by qindapao** [comment]
This may also be good.But we can lower the priority a little.

wiri arrow and angled arrow Can be linked to each other

**Comment by nkh** [comment]
@qindapao can they? lol, I have to check that

**Comment by qindapao** [comment]
@nkh I mean, if the function mentioned in your topic is realized, it will be fine. It will be fun, but it shouldn't be possible now.

**Comment by qindapao** [comment]
My English expression is still easy for you to misunderstand. :-D

**Comment by nkh** [comment]
a connector or centered connector is more flexible solution

a group object that lets non connected arrow ends be moved would also be useful

finally, non disconnectable arrow ends would make it simpler to create composite objects

**Comment by qindapao** [comment]
A long time ago, the version was limited. But since you created two group elements.Asciio becomes infinitely possible.We have the basic shapes, through which we can create other shapes. These are all left to users.

We all only use its basic functions, and there may be smart users who use it to complete graphics that we can't imagine.

I used to want to create five-pointed stars, hexagons and so on.But then I figured it out. These can all be constructed by combining elements, without spending time writing these codes.

Unfortunately, too few people like text and command-line tools. They are all attracted by the fancy graphical interface.

As you said, I later realized that we still have connectors. They match the arrows perfectly.

**Comment by qindapao** [comment]
I also used it to draw a flow chart at work today.I have drawn many flowcharts now. But they are all in the company.

**Comment by nkh** [comment]
@qindapao maybe it's possible to anonymize the flowcharts, ie replace text with text that's not relevant to your company, then we could use them as examples.

I found this on the internet!

![screenshot_2023-10-05_14-34-39](https://github.com/nkh/P5-App-Asciio/assets/45409/0e6aef0b-c68c-49fb-a16a-86f79351869f)


When it comes to making new objects from other objects, I think we already have quite a few requirements that would help, what's needed is a better interface to handle them, what's missing is an easy interface to create/save/load those elements.

#30 #31 #32 #21

**Comment by nkh** [comment]
@qindapao it's possible to make flowcharts anonyme, you keep the boxes and arrow but change the text to something irrelevant. The examples in the README come from real graphs  I made at work but just changed names.

Large flowchart:
![screenshot_2023-10-05_14-34-39](https://github.com/nkh/P5-App-Asciio/assets/45409/81342742-1c46-4a28-b470-e63602f3ec97)

**Comment by qindapao** [comment]
@nkh This text picture is very interesting, especially this candlestick.

My company is isolated from the network, so the data inside can't be taken out.

But it doesn't matter. When I have a good idea, I can spend some time recreating some sample flowcharts.I have drawn a text diagram illustrating a PCIE register, which can be used for cross mode description.PCIE protocol is public, and we can use it outside.I'll draw another one.

After the release of 1.9, we can consider optimizing the stencil system.
