### ISSUE TITLE
Cross mode error

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#51]
@qindapao 

I started testing the cross mode and I like it! 

I found an error, you're not the only one good at it ;)

![cross_bug](https://github.com/nkh/P5-App-Asciio/assets/45409/35a3e59d-315f-47bc-840e-4661e5b0bc36)

here's the asciio file

[cross.asciio.gz](https://github.com/nkh/P5-App-Asciio/files/11919683/cross.asciio.gz)

Please post, in this thread, the asciio files you're using in the small videos you made.

**Comment by nkh** [comment]
Where's the normal_filler_background color used?

**Comment by nkh** [comment]
Another one

![cross_bug2](https://github.com/nkh/P5-App-Asciio/assets/45409/fc1dbc44-0640-41a2-910f-55628e824ff1)


I use these colors

		cross_element_backgroud => [1, 1, 1],
		cross_filler_background => [1, 0.9, 0.9],
		normal_filler_background => [0, 1, 0],

**Comment by qindapao** [comment]
> @qindapao
> 
> I started testing the cross mode and I like it!
> 
> I found an error, you're not the only one good at it ;)
> 
> ![cross_bug](https://user-images.githubusercontent.com/45409/250171272-35a3e59d-315f-47bc-840e-4661e5b0bc36.gif)
> 
> here's the asciio file
> 
> [cross.asciio.gz](https://github.com/nkh/P5-App-Asciio/files/11919683/cross.asciio.gz)
> 
> Please post, in this thread, the asciio files you're using in the small videos you made.

[demo.zip](https://github.com/nkh/P5-App-Asciio/files/11924051/demo.zip)

Are you saying the problem is the arrow is missing? But the cross mode does not cause the element to disappear.let me run your graph and see

**Comment by qindapao** [comment]
https://github.com/nkh/P5-App-Asciio/issues/51#issuecomment-1615111473

![cross_mode_front_and_back](https://github.com/nkh/P5-App-Asciio/assets/109883544/9477fdbc-8d8a-4514-ad40-3b5ba0a55268)

For this problem, it is related to the front and back of the element. If the box is in the background, then the arrow crosses it to generate the plus sign. Otherwise some characters are obscured and no plus sign will be generated.

The user can get the desired result by adjusting the front and back. I think it's best not to destroy the front-back relationship of elements.

In addition, I am also quite entangled in the choice of cross fillers in ascii mode (unicode is simple and unambiguous). Is it appropriate to use plus signs or dots and backticks when three sides intersect? What is your opinion?

For the dots and backticks that intersect on three sides, I refer to the rules of existing elements so as not to damage the style.

**Comment by qindapao** [comment]
![image](https://github.com/nkh/P5-App-Asciio/assets/109883544/c8f48357-5952-448d-a2e7-a49b2f03094d)

In this case, I didn't set the fillers because if there were only dots and backticks vertically, the box would look weird.

**Comment by qindapao** [comment]
![image](https://github.com/nkh/P5-App-Asciio/assets/109883544/64e204ee-addd-4d83-a695-17644d6b8820)

You see here, only the plus sign takes into account the possibility of dots and backticks appearing up, down, left, and right.

**Comment by qindapao** [comment]
https://github.com/nkh/P5-App-Asciio/issues/51#issuecomment-1615389264
![arrow_disappear](https://github.com/nkh/P5-App-Asciio/assets/109883544/b1f801c9-b56f-4904-bd11-7a5ae1994d51)

I did an experiment with your asciio file, and found that the disappearance of the arrows should have nothing to do with the cross mode, and it should be a problem elsewhere.

**Comment by qindapao** [comment]
> Where's the normal_filler_background color used?

If ordinary fillers are converted into cross fillers, they can be correctly retained and deleted, and these elements need to be different from normal elements.

Their special identities need to be identified to tell users that they are not real elements.

**Comment by nkh** [comment]
# disappearing arrow

Ah, I see now why the arrow disappears! Well it doesn't!

I think it's re-routed on top of the other one. this is a good example and I will use it in the documentation

# small box not crossed

I think you made a good choice not showing the crossing when the result would look weird with a row of dots, maybe a '+' sign would be good, as in your example, let me think about it a bit longer, in the worst case we can have it an option.

ASCII is limited and that's why I like it :)


# fillers

I still don't get it, please make me a video when you have time

**Comment by qindapao** [comment]
I noticed a detail when you said that. The arrow flashed and then disappeared, like the arrow attached below arrow,Use debug to find that it is still there?.

normal fillers and color.

In fact, simply speaking, it is to distinguish it from the user's own elements. So that they don't have to manipulate these elements.Even after they enter the normal mode, the user's misoperation leads to the the position of the fillers is disordered.Then it is convenient to identify them, select them, and then delete them.

What do you think of this explanation?

If you still don't understand or feel a little redundant.When I have time, I will make a video to show you clearly why we need ordinary filler and give it a color.It's a pity that I was in the company this afternoon.But my spoken English is very poor.I guess I can only do silent video,The English I speak is Chinglish:)

**Comment by qindapao** [comment]
Do you think giving it a color will make the normal elements after the cross elements are converted look weird?

It seems really reasonable. Let me see if there is a problem if we don't give them color.It doesn't seem to be a big problem, after all, it will be deleted automatically after entering cross mode. As long as users don't sabotage(For example, the normal fillers are deliberately placed in various positions of the diagram, which can only be found through global selection), it's not a big problem.

**Comment by nkh** [comment]
I will wait for a video :)  text on the vide will be fine. Being able to make videos, even without voice, is a good skill when documenting and documenting is part of development.  

I'm not expecting anyone to speak the language I speak, I'm willing to make efforts so we understand each other, even with small scribbles on a napkin if necessary.

A fun story: I was in Singapore and needed to buy a book (when that was still a thing), I called the bookshop and asked a question, I understood nothing to the answer so I said "Sorry but I don't speak Chineses" and got a slow spoken answer ... "I am speaking English!", Singrish was more like it ;)
