### ISSUE TITLE
Refactor Cross.pm

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#52]
@qindapao 

I had a look at cross .pm, I'll look at Ascii.pm when I have time, and I refactored it a bit in this branch https://github.com/nkh/P5-App-Asciio/commits/refactor_cross

I propose you take that code and continue refactoring it. I haven't tested it but I feel confident that 

The things I recommend:
- study how I made some of the code shorter
- remove all superfluous parentheses, I changed some code that shows that
- define some constants for the magic variable 0, 1, 2, 3 so someone who is not familiar with it can understand
- there are a few hundred lines of code that are boiler plate, isn't there a way to generalize it, I wrote an example with sub select_cross_elements_type, but that one was simpler

Once the code is refactored we can discuss how to make it faster if necessary, I have some ideas. What's the size it starts to feel slow? tens of boxes, hundreds, thousands?

**Comment by qindapao** [comment]
@nkh 
Your suggestions are very good, I will continue to refactor according to your suggestions, it just needs to take some time.

Regarding performance, I will test it as soon as possible.

Performance bottlenecks mainly come from two aspects:

1. transform_elements_to_ascii_two_dimensional_array_for_cross_mode
The loop nesting of this function is relatively deep, and I don't know the specific performance.And characters are processed one by one.
2. In fact, we don't care about the text in the box, but it also participates in the calculation. However, they cannot be ignored because of the problem of character coverage.One problem with ignoring them is that hidden cross elements are considered to be in the foreground, generating fillers that shouldn't be generated.
3. for $cross_index (@{$index_ref})
It may be that when there are too many points filled, the cycle base will become larger.

Leave all of this for later, let me solve the basic refactoring problem first. In fact, in order to optimize performance, I have used two caches.

**Comment by nkh** [comment]
You just can merge my changes and check them (I did some test runs but not enough)., I won't touch that file again. performance later, I agree,

I tried with a just ten or so boxes and arrow and it was fast enough then.

since  you'll be refactoring continuously I'll close this ticket.
