### ISSUE TITLE
Refactoring: Remove Cross code from group.pm

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#80]

**Comment by qindapao** [comment]
@nkh 

group.pm At present, there is no code related to cross mode, the only thing there is the USE_CROSS_MODE variable set for export. Exporting to strip group1 we need to preserve this variable. Otherwise, strip group1 cannot be crossed in cross mode.

because the characters are frozen

Characters in strip group 1 no longer overwrite each other. So the cross characters need to be preserved when exporting.
