### ISSUE TITLE
Add border connection for ellipse and rhombus

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#96]
@nkh 

Found out today that the two shapes are missing this.I have added and removed some redundant code, please check

https://github.com/qindapao/P5-App-Asciio/commit/08d65393077297cdaaab54adef021ea3386383d3

**Comment by nkh** [comment]
why are you removing this?

![screenshot_2023-07-11_16-11-05](https://github.com/nkh/P5-App-Asciio/assets/45409/7260613f-3316-49bb-80e1-c7c21c77b610)

**Comment by qindapao** [comment]
@nkh 

You are mistaken. I removed the old function before, and the code you added has not been removed.

**Comment by qindapao** [comment]
@nkh 

Yours is this function.

make_selection_unicode

**Comment by nkh** [comment]
@qindapao merged

**Comment by qindapao** [comment]
Unicode slashes don't look so beautiful.

**Comment by nkh** [comment]
I disagree, the triangle looks good and the other shapes are useful, specially the ellipse.

Only the triangle renders well in SVG but it's because you made the effort to make it look good in ASCII. If we want something that looks OK in ASCII and good in SVG we should follow this. https://github.com/blampe/goat or this https://ivanceras.github.io/content/Svgbob/Circles.html, https://ivanceras.github.io/content/Svgbob/Specification.html

You can see in the circle specification that it doesn't look as good as yours in ASCII and it doesn't scale.







![screenshot_2023-07-11_16-43-52](https://github.com/nkh/P5-App-Asciio/assets/45409/d8ac7321-1b07-48b8-b9fb-b0ec55f5c0b3)

**Comment by qindapao** [comment]
@nkh 

I like ellipses, which cost me a lot of effort.

It's just not easy to find suitable unicode characters.

It looks better in ascii.I still don't like using svg.
Our ellipse is better.We don't have to sacrifice our standards to meet other software.As for the cooperation with them, we can get a special shape to meet their interfaces in the future.But I don't think these priorities are high.

After we try to launch 1.9, it may be the most meaningful thing to study web ui.

**Comment by qindapao** [comment]
@nkh 

You may have misunderstood, but I definitely like other shapes.I wrote the rhombus. How could I not like it?It's just that unicode slashes look a little unnatural.

It's just that other shapes are not easy to find suitable unicode characters.But it doesn't matter.


My English expression is sometimes misleading. After all, I don't live in an English environment. Please forgive me.
